import type { PromptTemplate } from './types';

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  // ── Marketing ──
  { id: 'mkt-1', name: 'Product Launch Script', description: 'Full go-to-market launch sequence with email, social, and ad copy', mindset: 'marketing', prompt: 'Create a comprehensive product launch campaign for [product name]. Include: launch email sequence (3 emails), social media posts for Instagram/Twitter/LinkedIn, and two ad copy variations (Facebook + Google). Target audience: [audience]. Key value proposition: [value prop]. Launch date: [date].' },
  { id: 'mkt-2', name: 'Email Campaign', description: 'Multi-touch email sequence with subject lines and CTAs', mindset: 'marketing', prompt: 'Design a 5-email drip campaign for [goal]. Include compelling subject lines, preview text, body copy, and CTAs for each email. Segment: [audience segment]. Tone: [professional/casual/urgent]. Include A/B test suggestions for subject lines.' },
  { id: 'mkt-3', name: 'Ad Copy Bundle', description: 'Paid ad copy for multiple platforms with hooks and CTAs', mindset: 'marketing', prompt: 'Write ad copy variations for [product/service] across Facebook, Google Search, and Instagram. Include: 3 headlines, 2 descriptions, primary text, and CTA buttons for each platform. Pain point: [pain point]. Unique selling proposition: [USP].' },

  // ── Sales ──
  { id: 'sal-1', name: 'Sales Pitch Deck', description: 'Persuasive presentation structure with talking points', mindset: 'sales', prompt: 'Create a sales pitch deck outline for [product/service]. Include: opening hook, problem statement, solution overview, demo flow, competitive advantages, pricing slide, case study/testimonial, objection handling notes, and closing slide with next steps. Target buyer: [persona].' },
  { id: 'sal-2', name: 'Cold Outreach Sequence', description: 'Multi-channel outreach campaign with follow-ups', mindset: 'sales', prompt: 'Write a cold outreach sequence for [product/service] targeting [persona]. Include: LinkedIn connection message, initial email, 3 follow-up emails (spaced 3-5 days), phone call script, and break-up email. Pain point: [pain point]. Social proof: [proof].' },
  { id: 'sal-3', name: 'Discovery Call Script', description: 'Structured discovery call with qualifying questions', mindset: 'sales', prompt: 'Create a discovery call script for [product/service]. Include: opening rapport builder, SPIN questions (Situation, Problem, Implication, Need-payoff), qualification criteria, demo transition, objection responses (top 5), and next steps/scheduling. Call duration: 30 minutes.' },

  // ── Startup ──
  { id: 'str-1', name: 'Investor Pitch Deck', description: '12-slide pitch deck with market sizing and traction', mindset: 'startup', prompt: 'Create an investor pitch deck outline for [startup name]. Include slides: cover, problem, solution, market size (TAM/SAM/SOM), business model, traction, competition, team, go-to-market, financials, funding ask, and vision. Stage: [pre-seed/seed/Series A]. Industry: [industry].' },
  { id: 'str-2', name: 'MVP Feature Spec', description: 'Minimal viable product scope with user stories', mindset: 'startup', prompt: 'Define an MVP spec for [product idea]. Include: core value proposition, 5-8 must-have features as user stories, nice-to-have features (post-MVP), tech stack recommendation, estimated timeline, success metrics, and first 100 users acquisition plan.' },
  { id: 'str-3', name: 'Go-To-Market Plan', description: 'Launch strategy with channels, timeline, and metrics', mindset: 'startup', prompt: 'Create a go-to-market plan for [product]. Include: target customer segments, positioning statement, pricing strategy, distribution channels, launch timeline (90 days), content/marketing plan, partnership opportunities, KPIs, and budget allocation.' },

  // ── E-commerce ──
  { id: 'eco-1', name: 'Product Listing Copy', description: 'High-converting product descriptions for online store', mindset: 'ecommerce', prompt: 'Write product listing copy for [product]. Include: SEO-optimized title, bullet points (5-7 key features), long description with benefits, specifications table, cross-sell suggestions, and FAQ section. Marketplace: [Amazon/Shopify/both]. Target keywords: [keywords].' },
  { id: 'eco-2', name: 'Cart Recovery Sequence', description: 'Abandoned cart email flow with incentives', mindset: 'ecommerce', prompt: 'Create a 3-email cart abandonment recovery sequence. Include: Email 1 (1 hour - reminder), Email 2 (24 hours - social proof), Email 3 (48 hours - incentive). Each email: subject line, preview text, body copy, CTA button text, and urgency elements.' },
  { id: 'eco-3', name: 'Seasonal Sale Campaign', description: 'Full promotional campaign for holiday/seasonal sale', mindset: 'ecommerce', prompt: 'Plan a seasonal sale campaign for [holiday/event]. Include: sale naming, discount structure, email teasers, launch communications, social media posts, homepage banner copy, and post-sale follow-up. Duration: [length]. Discount: [percentage].' },

  // ── Photo ──
  { id: 'pho-1', name: 'Product Photography Brief', description: 'Commercial product shoot with lighting and composition specs', mindset: 'photo', prompt: 'Create a detailed product photography brief for [product type]. Include: 5 shot concepts, camera settings (aperture, shutter, ISO), lighting setup diagrams, styling notes, background recommendations, and post-processing guidelines. Style reference: [clean/moody/lifestyle/editorial].' },
  { id: 'pho-2', name: 'Portrait Session Plan', description: 'Complete portrait shoot plan with poses and lighting', mindset: 'photo', prompt: 'Plan a portrait photography session for [subject type]. Include: location recommendations, 8 pose ideas, lighting setups (key, fill, rim), lens recommendations, wardrobe suggestions, and mood board description. Style: [editorial/casual/dramatic].' },
  { id: 'pho-3', name: 'Social Media Content Pack', description: 'Instagram/TikTok visual content strategy with shot list', mindset: 'photo', prompt: 'Create a social media photo content plan for [brand/person]. Include: 12 shot concepts, optimal aspect ratios per platform, color palette guidance, props list, caption hooks, and hashtag strategy. Aesthetic: [minimal/vibrant/dark/natural].' },

  // ── Video ──
  { id: 'vid-1', name: 'Video Storyboard', description: 'Scene-by-scene storyboard with shot types and transitions', mindset: 'video', prompt: 'Create a detailed video storyboard for a [duration]-minute [type: promo/explainer/documentary]. Include: scene descriptions, shot types, camera movements, transitions, audio notes, and pacing. Topic: [topic]. Tone: [energetic/calm/dramatic].' },
  { id: 'vid-2', name: 'YouTube Script', description: 'Full YouTube video script with hook, content, and CTA', mindset: 'video', prompt: 'Write a YouTube video script for a [duration]-minute video about [topic]. Include: hook (first 5 seconds), intro, main content with timestamps, B-roll suggestions, lower third text, end screen CTA, and description with keywords.' },
  { id: 'vid-3', name: 'Short-Form Video Series', description: 'TikTok/Reels content batch with hooks and trends', mindset: 'video', prompt: 'Plan a 7-day short-form video series for [platform] about [topic]. Each video: hook line, content outline (15-60 sec), trending audio suggestion, text overlay script, hashtags, and posting time. Goal: [grow followers/drive sales/educate].' },

  // ── Design ──
  { id: 'des-1', name: 'Landing Page Wireframe', description: 'Conversion-focused landing page layout with sections', mindset: 'design', prompt: 'Design a landing page wireframe for [product/service]. Include: hero section, social proof, features grid, pricing table, FAQ accordion, testimonials, and final CTA. Target: [audience]. Style: [minimal/bold/playful].' },
  { id: 'des-2', name: 'Design System Tokens', description: 'Complete design token set with colors, typography, spacing', mindset: 'design', prompt: 'Create a design system token spec for [brand/product]. Include: color palette (primary, secondary, neutral, semantic), typography scale, spacing scale, border radius, shadow levels, and component variants for buttons, inputs, and cards.' },
  { id: 'des-3', name: 'Mobile App UI Flow', description: 'User flow with screen descriptions and interactions', mindset: 'design', prompt: 'Design a mobile app UI flow for [app concept]. Include: onboarding (3 screens), main dashboard, navigation structure, key feature screens, settings page, and empty states. Describe each screen: layout, elements, interactions. Platform: [iOS/Android/both].' },

  // ── Music ──
  { id: 'mus-1', name: 'Track Production Brief', description: 'Full production spec with arrangement and mix notes', mindset: 'music', prompt: 'Create a music production brief for a [genre] track. Include: BPM, key, arrangement structure (intro/verse/chorus/bridge/outro with bar counts), instrument palette, reference tracks, mix priorities, and mastering notes. Duration: [length]. Purpose: [streaming/sync/background].' },
  { id: 'mus-2', name: 'Playlist Curation Guide', description: 'Themed playlist strategy with mood arc and track selection', mindset: 'music', prompt: 'Curate a [mood/theme] playlist concept. Include: playlist name, cover art description, 20 track suggestions with artist/song, mood arc (energy flow), genre mix percentages, target listener profile, and Spotify description copy.' },
  { id: 'mus-3', name: 'Sound Design Spec', description: 'Custom sound design for video, game, or app', mindset: 'music', prompt: 'Create a sound design specification for [project type]. Include: ambient background layers, UI sound effects list, notification sounds, transition sounds, music cues, volume levels, and implementation notes. Style: [futuristic/organic/minimal/playful].' },

  // ── Developer ──
  { id: 'dev-1', name: 'Code Review Checklist', description: 'Systematic code review with best practices', mindset: 'developer', prompt: 'Create a code review checklist for a [language/framework] project. Cover: architecture patterns, performance, security vulnerabilities, error handling, testing coverage, naming conventions, and documentation. Include severity levels for each item.' },
  { id: 'dev-2', name: 'Technical Documentation', description: 'Full technical docs with API reference and examples', mindset: 'developer', prompt: 'Write technical documentation for [feature/API]. Include: overview, architecture description, setup guide, API reference with request/response examples, error codes, rate limits, authentication flow, and FAQ section.' },
  { id: 'dev-3', name: 'API Design Spec', description: 'RESTful API specification with endpoints and schemas', mindset: 'developer', prompt: 'Design a RESTful API for [system/feature]. Include: endpoint list with HTTP methods, request/response schemas (JSON), authentication strategy, pagination, error handling, rate limiting, and versioning strategy. Follow OpenAPI 3.0 conventions.' },

  // ── Data ──
  { id: 'dat-1', name: 'Dashboard Spec', description: 'Analytics dashboard with KPIs and visualization types', mindset: 'data', prompt: 'Design an analytics dashboard for [business/product]. Include: 8-12 key metrics with visualization types, data sources, refresh rates, filter options, drill-down capabilities, alert thresholds, and executive summary section.' },
  { id: 'dat-2', name: 'Data Pipeline Architecture', description: 'ETL pipeline design from source to visualization', mindset: 'data', prompt: 'Design a data pipeline for [use case]. Include: data sources, ingestion method, transformation steps, storage layer, processing framework, orchestration tool, data quality checks, and output format. Scale: [volume].' },
  { id: 'dat-3', name: 'A/B Test Design', description: 'Experiment setup with hypothesis and statistical plan', mindset: 'data', prompt: 'Design an A/B test for [feature/change]. Include: hypothesis, primary and secondary metrics, sample size calculation, test duration, segmentation criteria, expected effect size, significance threshold, and rollout plan.' },

  // ── AI ──
  { id: 'ai-1', name: 'Prompt Chain Design', description: 'Multi-step prompt pipeline for complex AI tasks', mindset: 'ai', prompt: 'Design a prompt chain for [complex task]. Include: chain overview, 3-5 prompt steps with inputs/outputs, context passing strategy, error handling, temperature settings per step, token budget, and quality evaluation criteria.' },
  { id: 'ai-2', name: 'RAG System Architecture', description: 'Retrieval-augmented generation system design', mindset: 'ai', prompt: 'Design a RAG system for [knowledge domain]. Include: document ingestion pipeline, chunking strategy, embedding model choice, vector database selection, retrieval algorithm, prompt template with context injection, and evaluation metrics.' },
  { id: 'ai-3', name: 'Fine-Tuning Data Spec', description: 'Training data format and curation guidelines', mindset: 'ai', prompt: 'Create a fine-tuning data spec for [use case]. Include: data format (JSONL), 5 example training pairs, quality criteria, minimum dataset size, data collection sources, preprocessing steps, validation split, and expected behavior changes.' },

  // ── Security ──
  { id: 'sec-1', name: 'Security Audit Checklist', description: 'Comprehensive security review for web applications', mindset: 'security', prompt: 'Create a security audit checklist for a [web app/API]. Include: OWASP Top 10, authentication review, authorization testing, input validation, encryption, logging and monitoring, dependency vulnerabilities, and incident response readiness.' },
  { id: 'sec-2', name: 'Incident Response Plan', description: 'Security incident playbook with roles and procedures', mindset: 'security', prompt: 'Write a security incident response plan for [organization type]. Include: incident classification, detection procedures, escalation matrix, containment steps, evidence preservation, communication templates, recovery procedures, and post-incident review.' },
  { id: 'sec-3', name: 'Penetration Test Scope', description: 'Pen test planning document with targets and rules', mindset: 'security', prompt: 'Define a penetration testing scope for [target system]. Include: objectives, in-scope systems/URLs, out-of-scope items, methodology (black/gray/white box), rules of engagement, timeline, reporting format, and remediation priority framework.' },

  // ── Legal ──
  { id: 'leg-1', name: 'Service Agreement', description: 'Contract template with key clauses and terms', mindset: 'legal', prompt: 'Draft a [service/consulting/SaaS] agreement template. Include: parties, scope of work, payment terms, IP rights, confidentiality, limitation of liability, termination, dispute resolution, force majeure, and governing law.' },
  { id: 'leg-2', name: 'Privacy Policy Draft', description: 'GDPR/CCPA compliant privacy policy', mindset: 'legal', prompt: "Write a privacy policy for [website/app]. Include: data collection types, usage purposes, third-party sharing, cookie policy, user rights, data retention, security measures, children's privacy, and contact info. Compliance: [GDPR/CCPA/both]." },
  { id: 'leg-3', name: 'Terms of Service', description: 'User agreement with liability and usage terms', mindset: 'legal', prompt: 'Draft terms of service for [platform/service]. Include: acceptance of terms, account creation, acceptable use, prohibited content, IP, limitation of liability, indemnification, termination, modifications, and dispute resolution.' },

  // ── Scientific ──
  { id: 'sci-1', name: 'Research Proposal', description: 'Grant-ready research proposal with methodology', mindset: 'scientific', prompt: 'Write a research proposal for [topic]. Include: abstract, introduction with literature review, research questions/hypotheses, methodology, expected results, timeline, budget estimate, ethical considerations, and references format.' },
  { id: 'sci-2', name: 'Literature Review', description: 'Systematic review of existing research', mindset: 'scientific', prompt: 'Create a literature review outline for [topic]. Include: search strategy, inclusion/exclusion criteria, screening process, data extraction template, synthesis approach, gap identification, and future research implications.' },
  { id: 'sci-3', name: 'Experiment Design', description: 'Controlled experiment with variables and analysis plan', mindset: 'scientific', prompt: 'Design an experiment to test [hypothesis]. Include: independent/dependent variables, control conditions, sample size justification, randomization, data collection instruments, statistical analysis plan, and potential confounds.' },

  // ── Medical ──
  { id: 'med-1', name: 'Patient Education Material', description: 'Clear medical information for patient understanding', mindset: 'medical', prompt: 'Create patient education material for [condition/procedure]. Include: plain language explanation, causes, symptoms, diagnostic process, treatment options, medications, lifestyle modifications, when to seek emergency care, and FAQ. Reading level: 6th grade.' },
  { id: 'med-2', name: 'Clinical Protocol', description: 'Standard operating procedure for clinical processes', mindset: 'medical', prompt: 'Write a clinical protocol for [procedure/condition]. Include: purpose, scope, patient selection, pre-procedure checklist, step-by-step procedure, monitoring, post-procedure care, complication management, and quality metrics.' },
  { id: 'med-3', name: 'Case Presentation', description: 'Structured clinical case presentation format', mindset: 'medical', prompt: 'Create a case presentation for [specialty]. Include: demographics, chief complaint, history of present illness, past history, medications, allergies, physical exam, differential diagnosis, diagnostic workup, and assessment/plan.' },

  // ── HR ──
  { id: 'hr-1', name: 'Job Description', description: 'Attractive job posting with role details and requirements', mindset: 'hr', prompt: 'Write a job description for [role title] at [company type]. Include: intro paragraph, responsibilities (8-10), required qualifications, preferred qualifications, salary range, benefits, culture statement, DEI commitment, and application instructions.' },
  { id: 'hr-2', name: 'Performance Review Template', description: 'Structured employee evaluation with goals and feedback', mindset: 'hr', prompt: 'Create a performance review template for [role type]. Include: self-assessment, manager assessment, achievements, improvement areas, SMART goals for next quarter, competency ratings (1-5 scale), career development points, and overall rating.' },
  { id: 'hr-3', name: 'Onboarding Checklist', description: '30-60-90 day new hire integration plan', mindset: 'hr', prompt: 'Design a 30-60-90 day onboarding plan for a new [role]. Include: pre-start prep, Day 1 schedule, Week 1 goals, 30/60/90-day milestones, mentor assignment, training modules, check-in schedule, and success metrics.' },

  // ── Content ──
  { id: 'con-1', name: 'Content Strategy Brief', description: '90-day content plan with themes and distribution', mindset: 'content', prompt: 'Create a 90-day content strategy for [brand/product]. Include: content pillars (3-5 themes), monthly themes, content mix ratios, editorial calendar template, SEO keywords per pillar, distribution channels, repurposing plan, and KPIs.' },
  { id: 'con-2', name: 'Blog Post Outline', description: 'SEO-optimized long-form article structure', mindset: 'content', prompt: 'Write a blog post outline for "[topic]". Include: SEO title, meta description, H2/H3 structure with word count targets, intro hook, key points, data suggestions, internal links, CTA placement, and FAQ section. Target keyword: [keyword].' },
  { id: 'con-3', name: 'Case Study Framework', description: 'Customer success story with measurable results', mindset: 'content', prompt: 'Create a case study for [client/project]. Include: headline with result, executive summary, client background, challenge, solution, implementation, measurable results with numbers, client quote placeholders, and CTA.' },

  // ── SEO ──
  { id: 'seo-1', name: 'Keyword Research Plan', description: 'Systematic keyword discovery and prioritization', mindset: 'seo', prompt: 'Create a keyword research plan for [website/niche]. Include: seed keywords (20), search intent categories, keyword clustering, volume/difficulty assessment, long-tail opportunities, competitor gap analysis, and content mapping.' },
  { id: 'seo-2', name: 'On-Page SEO Audit', description: 'Page-level optimization checklist with priorities', mindset: 'seo', prompt: 'Create an on-page SEO audit for [URL/page type]. Include: title tag, meta description, header hierarchy, keyword density, internal linking, image alt text, schema markup, page speed, mobile responsiveness, and Core Web Vitals.' },
  { id: 'seo-3', name: 'Link Building Strategy', description: 'Outreach plan for building quality backlinks', mindset: 'seo', prompt: 'Design a link building strategy for [website]. Include: backlink profile assessment, competitor analysis, 5 link building tactics with steps, outreach templates, target site criteria, content assets to create, timeline, and success metrics.' },

  // ── Social ──
  { id: 'soc-1', name: 'Social Media Calendar', description: '30-day content calendar with post types and timing', mindset: 'social', prompt: 'Create a 30-day social media calendar for [brand] on [platforms]. Include: daily post types, caption templates, hashtag sets, optimal posting times, engagement prompts, story/reel ideas, and weekly themes. Goal: [followers/engagement/sales].' },
  { id: 'soc-2', name: 'Viral Content Formula', description: 'High-shareability content framework with hooks', mindset: 'social', prompt: 'Design 10 viral content concepts for [niche/brand]. Each: hook line, content structure, visual description, caption template, trending audio suggestion, hashtag strategy, and CTA. Platform: [TikTok/Instagram/both].' },
  { id: 'soc-3', name: 'Influencer Brief', description: 'Campaign brief for influencer partnerships', mindset: 'social', prompt: "Write an influencer collaboration brief for [campaign]. Include: brand overview, objectives, target audience, content requirements, dos/don'ts, deliverables, timeline, usage rights, FTC disclosure, and compensation structure." },

  // ── Email ──
  { id: 'eml-1', name: 'Welcome Email Series', description: '5-email onboarding sequence for new subscribers', mindset: 'email', prompt: 'Create a 5-email welcome series for [business]. Email 1: warm welcome. Email 2: best content. Email 3: social proof. Email 4: exclusive offer. Email 5: engagement prompt. Each: subject line, preview text, body copy, CTA, and send timing.' },
  { id: 'eml-2', name: 'Newsletter Template', description: 'Recurring newsletter structure with sections', mindset: 'email', prompt: 'Design a weekly newsletter template for [brand/topic]. Include: header, greeting, main story, 3 curated links, product spotlight, community highlight, CTA section, and footer. Tone: [professional/friendly/witty].' },
  { id: 'eml-3', name: 'Re-Engagement Campaign', description: 'Win-back sequence for inactive subscribers', mindset: 'email', prompt: "Write a re-engagement campaign for inactive subscribers. Include: Email 1 (miss you), Email 2 (what's new), Email 3 (special offer), Email 4 (last chance + survey). Each: subject line, preview text, body, CTA, and sunset criteria." },
];
